### ISSUE TITLE
Issue with rsync not deleting files on remote host

### ISSUE THREAD

**Issue by age992** [Inf166/action-sshpass-rsync#1]
Hey Joel,

thank you for this useful action! We are currently trying to workout the deployment of our student project using this action but we ran into one problem: When deleting files in our github repo, the corresponding file on the remote host is not being deleted (all other files with changes are updated tho). I have made sure that "local" and "remote" are setup up in a way that the remote folder should be overwritten by the local folder. However, the problem remains.
Can you help us? :(

Thank you very much!

**Comment by vintertown** [comment]
Hey Joel,

got the same problem. Can you update your git repo? That would be fantastic! :) 

Thank you very much!

**Comment by vintertown** [comment]
https://www.oreilly.com/library/view/linux-shell-scripting/9781785881985/0121ca8d-0ae6-47bc-9132-c08614aa343f.xhtml

Maybe this helps..

**Comment by mai-space** [comment]
Thank you for your contribution to this action. I will check the source and update tomorrow. You guys can also make a pull request if you want to - so your contribution will be seen in the git log.

Feel free - either way, I will update tomorrow. Please tell me if the solution will work for you.

Best regards!

**Comment by mai-space** [comment]
I have published the version 1.4 with the requested changes. Please tell me if this works for you.
https://github.com/Inf166/action-sshpass-rsync/releases/tag/v1.4

**Comment by age992** [comment]
Hey, thank you for your very quick help.

I tried to use 1.4 but I got the error: 
_rsync: Failed to exec h: No such file or directory (2)_

I searched for a solution and could only find that there are some issues when using the "-e" and "--delete" option of rsync in wrong order within the command. I got it working on my local machine and created a pull request. I hope it works on your machine aswell!

**Comment by mai-space** [comment]
Again, thank you.

I read that the delete option should be last, but in my understanding it just had to be the last option not the last attribute passed. But well, you seem to have solved it. I'm gonna check if all options are in your pull request and might edit the commit message because of the guidelines I am following in all my projects. But thank you for your bugfix and I will merge it asap.

**Comment by mai-space** [comment]
@age992 please feel free to test and use version 2 with your changes and some clean up and commit message edits. As the version description states, I am planning on cleaning up my versions. But I will wait until most projects use v2.

As soon as all your problems are solved and you confirm this to me, I will close this issue.

**Comment by age992** [comment]
@Inf166 I am sorry, but I still get an error: 
_rsync: Failed to exec -l: No such file or directory (2)_
This error is similar to the last one. I think the -e option for the rsync command must be the last one before `"ssh -p $INPUT_PORT"`... etc., for whatever reason (at least it worked like that on my machine). Thank you for your support!!

**Comment by mai-space** [comment]
You know the drill. Version 2.1 is the go to.

**Comment by mai-space** [comment]
I really gotta check out the documentation of rsync - it can't be that complicated to implement a version of this action that respects all aspects of modern deployment. We aren't really doing anything new here 😃

**Comment by age992** [comment]
@Inf166 Thank you so much. Our deployment is finally working. Without your help this wouldnt have worked out in time (deadlines coming soon...)! Thank you!

**Comment by mai-space** [comment]
I feel you - I only made this action because there were noone else supplying a solution for crappy hosts. I hope this action will now solve your problems for now. But as I said, I will improve on rsync later on this year. It really bothers me that the symlinks didn't work.

Kind regards!
